### ISSUE TITLE
Core PR?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/transliteration#1]
Hi @jdanthinne 
https://github.com/backdrop/backdrop-issues/issues/904 says this module is to be merged into core. Wondering if you were planning to help with that? 1.3.0 comes out on January 15, so we have about 1 month left, so I'm trying to get the 1.3.0 issues rolling.

**Comment by jdanthinne** [comment]
I don't have much time right now but I'd be happy to help. Were you planning to include the module simply into core/modules (and use its functions where relevant) or directly include the functions into the core functions?

**Comment by docwilmot** [comment]
Any little help would be good; at least if you could push the initial PR? 
Some integration is definitely planned - https://github.com/backdrop/backdrop-issues/issues/904#issue-73859248, but those could be subsequent work.

**Comment by jdanthinne** [comment]
Allright. Which branch do you recommend me to work on? 1.x? 1.2.x?

**Comment by docwilmot** [comment]
1.x please. thanks.

**Comment by jdanthinne** [comment]
https://github.com/backdrop/backdrop/pull/1133
